import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FlexLayout from "@/UI/layout/FlexLayout";
import TopNavBar from "@/UI/Navbar/TopNavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
      <title>SMASH UP!</title>
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Bagel+Fat+One&family=Bungee+Spice&family=Honk&display=swap');
      </style>
    </head>
    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{width: "100%"}}>
        <TopNavBar/>
        <FlexLayout>
            {children}
        </FlexLayout>
      </body>
    </html>
  );
}
