import {ArcherModel} from "@/model/ArcherModel";
import {WarriorModel} from "@/model/WarriorModel";
import {MageModel} from "@/model/MageModel";
import {NecroModel} from "@/model/NecroModel";
import {ClericModel} from "@/model/ClericModel";

export const characterConfigs = [
    { id: "Archer",
      label: "궁수",
      src: "/job/archer.png",
      color: "greenyellow",
      description: "보고 피하기에는 이미 늦었다!\n강력한 화살이 순식간에 숨통을 끊는다!",
      skillLabels: ["신궁의 화살","맹독 화살","폭렬 화살","얼음 송곳","독사의 포효","유성 사격"],
      skillDescs: [
        "정밀한 화살이 적을 꿰뚫습니다.",
        "맹독을 머금은 화살이 적의 생명을 갉아먹습니다.",
        "강력한 폭발을 일으키는 화살을 발사합니다.",
        "차가운 화살이 적의 움직임을 둔화시킵니다.",
        "집중한 한 발이 독을 머금고 적을 관통합니다.",
        "하늘에서 떨어지는 별처럼 강렬한 화살이 적을 덮칩니다.",
      ],
      skillIcons: [
        "/skill/v2/archer/arrow_icon.png",
        "/skill/v2/archer/poisonArrow_icon.png",
        "/skill/v2/archer/explosionArrow_icon.png",
        "/skill/v2/archer/IceArrow_icon.png",
        "/skill/v2/archer/PoisonSpore_icon.png",
        "/skill/v2/archer/Starfall_icon.png",
      ],
      ModelComponent: ArcherModel},
    { id: "Warrior",
      label: "전사",
      src: "/job/warrior.png",
      color: "#DCAD67",
      description: "앞길을 막는 자는, 전부 부숴버린다!\n누구도 부정할 수 없는 근접전의 최강자!",
      skillLabels: [
        "참살의 도끼",
        "강화의 비약",
        "광폭 돌진",
        "멸절의 도끼",
        "광전사의 피",
        "멈출 수 없는 광란",
      ],
      skillDescs: [
        "강력한 도끼질로 주변의 적을 단숨에 베어냅니다.",
        "이동속도가 감소하지만 체력을 회복하고 방어가 증가합니다.",
        "거침없는 돌진으로 적을 쓸어버립니다.",
        "거대한 도끼를 내리쳐 전장을 가르며 눈앞의 생명들을 멸합니다.",
        "광전사의 기운을 받아 체력을 희생하여 압도적인 힘을 발휘합니다.",
        "분노가 극에 달한 돌진으로 경로의 모든 적에게 파멸을 안깁니다.",
      ],
      skillIcons: [
        "/skill/v2/warrior/slash_icon.png",
        "/skill/v2/warrior/powerBody_icon.png",
        "/skill/v2/warrior/charge_icon.png",
        "/skill/v2/warrior/powerSlash_icon.png",
        "/skill/v2/warrior/powerPowerBody_icon.png",
        "/skill/v2/warrior/powerCharge_icon.png",
      ],
      ModelComponent: WarriorModel},
      { id: "Mage",
        label: "마법사",
        src: "/job/mage.png",
        color: "deepskyblue",
        description: "이 세계의 법칙은 내가 다시 쓴다!\n변수를 창조하는 마법의 전문가!",
        skillLabels: [
          "화염구",
          "신의 심판",
          "빙설의 포효",
          "종말의 유성",
          "천상의 격노",
          "극한의 서리",
        ],
        skillDescs: [
          "타오르는 화염구를 발사하여 적을 불태웁니다.",
          "천둥을 불러 하늘의 분노를 적에게 내립니다.",
          "차가운 폭풍이 몰아쳐 적을 얼려버립니다.",
          "거대한 유성이 떨어져 모든 것을 불태웁니다.",
          "신의 분노가 연속적인 천둥으로 쏟아집니다.",
          "점차 퍼지는 영원의 겨울이 적을 얼어붙게 만듭니다.",
        ],
        skillIcons: [
          "/skill/v2/mage/fireball_icon.png",
          "/skill/v2/mage/thunder_icon.png",
          "/skill/v2/mage/IceArea_icon.png",
          "/skill/v2/mage/meteor_icon.png",
          "/skill/v2/mage/ThunderStrorm_icon.png",
          "/skill/v2/mage/FreezeArea_icon.png",
        ],
        ModelComponent: MageModel},
      { id: "Necromancer",
        label: "네크로맨서",
        src: "/job/necromancer.png",
        color: "#9D71BD",
        description: "산 자는 두려워하고 죽은 자는 따른다!\n전장을 장악하는 망자의 군주",
        skillLabels: [
          "망령의 급습",
          "영혼 소용돌이",
          "지옥의 갈증",
          "망령의 추격자",
          "영혼의 심연",
          "저주의 연소",
        ],
        skillDescs: [
          "망령이 어둠을 가르고 장애물을 무시하며 돌진합니다.",
          "영혼의 소용돌이가 적들을 중심으로 끌어모읍니다.",
          "지옥불이 적을 불태우고 사용자의 생명을 치유합니다.",
          "선택된 영혼이 눈앞의 적을 집요하게 추적합니다.",
          "저주받은 늪이 이동을 방해하고 생명을 갉아먹습니다.",
          "중독된 불꽃이 적에게 지속적인 고통을 안깁니다.",
        ],
        skillIcons: [
          "/skill/v2/necro/PhantomAttack_icon.png",
          "/skill/v2/necro/SoulVortex_icon.png",
          "/skill/v2/necro/InfernalFlask_icon.png",
          "/skill/v2/necro/PhantomSmart_icon.png",
          "/skill/v2/necro/SoulSwamp_icon.png",
          "/skill/v2/necro/InfernalPoison_icon.png",
        ],
        ModelComponent: NecroModel},
        { id: "Cleric",
          label: "성직자",
          src: "/job/priest.png",
          color: "yellow",
          description: "빛이 머무는 자, 생명을 부여하고 심판을 내리다!\n하늘의 뜻을 전하는 신의 사도",
          skillLabels: [
            "성스러운 광휘",
            "신성 충격파",
            "성스러운 치유",
            "심판의 탄환",
            "심판의 광선",
            "천상의 치유",
          ],
          skillDescs: [
            "신성한 구체가 적을 심판합니다.",
            "전방으로 퍼지는 고결한 파동이 적을 밀쳐냅니다.",
            "거룩한 기운이 범위 안의 모두를 치유합니다.",
            "성스러운 총알을 일제히 발사합니다.",
            "강력한 신성의 광선이 전장을 가로지릅니다.",
            "거룩한 기운이 치유와 함께 방어의 축복까지 내려줍니다.",
          ],
          skillIcons: [
            "/skill/v2/cleric/HollyAttack_icon.png",
            "/skill/v2/cleric/HolyBeam_icon.png",
            "/skill/v2/cleric/HolyRecovery_icon.png",
            "/skill/v2/cleric/HollySpear_icon.png",
            "/skill/v2/cleric/HolyBeamPlus_icon.png",
            "/skill/v2/cleric/HolyHeal_icon.png",
          ],
          ModelComponent: ClericModel}
  ];